### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pcl_ply2obj': 'pcl_ply2obj'

### ISSUE THREAD

**Issue by Yanxing-Shi** [navjot95/pointNetGraspClassifier#1]
Hi,thank you for sharing this code.But I make this error,please help me out.
```bash
(pytorch) user@505:~/code/grasp-pointnet/dex-net/apps$ python read_file_sdf.py
Traceback (most recent call last):
  File "read_file_sdf.py", line 62, in <module>
    generate_obj_from_ply(i+"/google_512k/nontextured.ply")
  File "read_file_sdf.py", line 48, in generate_obj_from_ply
    p = subprocess.Popen(["pcl_ply2obj", base + ".ply", base + ".obj"])
  File "/home/user/anaconda3/envs/pytorch/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pcl_ply2obj': 'pcl_ply2obj'
```

**Comment by lwohlhart** [comment]
Hi, I also just encountered the same error.
You need to install the pcl-tools
```bash
sudo apt-get install pcl-tools
```
This should make the pcl_ply2obj binary available :-)

**Comment by Josin1** [comment]
> Hi, I also just encountered the same error.
> You need to install the pcl-tools
> 
> ```shell
> sudo apt-get install pcl-tools
> ```
> 
> This should make the pcl_ply2obj binary available :-)

Where should we install pcl-tools?
